### ISSUE TITLE
Doesn't resize past a certain point

### ISSUE THREAD

**Issue by mobitar** [dagjaneiro/authenticator-editor#1]
<img width="298" alt="Screen Shot 2019-07-08 at 10 11 33 AM" src="https://user-images.githubusercontent.com/3277844/60821525-4d2ddc80-a169-11e9-9eb7-7a4dc3f2f086.png">

Probably at this width everything should just stack vertically

**Comment by dagjaneiro** [comment]
After the latest changes it's now displayed like this:

![image](https://user-images.githubusercontent.com/10207818/60987156-ec54fe80-a338-11e9-89c6-deda626fae0f.png)
